#!/usr/bin/env python3
"""Generate an OpenWrt pbr custom user file from a CIDR list."""

from __future__ import annotations

import argparse
import ipaddress
import pathlib
import sys
import time
import urllib.request

DEFAULT_SOURCE = (
    "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt"
)


def read_source(source: str) -> str:
    path = pathlib.Path(source)
    if path.is_file():
        return path.read_text(encoding="utf-8")

    request = urllib.request.Request(
        source, headers={"User-Agent": "pbr-geoip-cn-generator/1.0"}
    )
    last_error: Exception | None = None
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return response.read().decode("utf-8")
        except Exception as error:  # pragma: no cover - only exercised on network errors
            last_error = error
            if attempt < 2:
                time.sleep(2**attempt)
    raise RuntimeError(f"unable to download {source}: {last_error}")


def parse_networks(raw: str) -> tuple[list[ipaddress.IPv4Network], list[ipaddress.IPv6Network]]:
    networks: set[ipaddress.IPv4Network | ipaddress.IPv6Network] = set()
    for line_number, line in enumerate(raw.splitlines(), start=1):
        value = line.split("#", 1)[0].strip()
        if not value:
            continue
        try:
            networks.add(ipaddress.ip_network(value, strict=True))
        except ValueError as error:
            raise ValueError(f"invalid CIDR at line {line_number}: {value}") from error

    collapsed4 = ipaddress.collapse_addresses(
        network for network in networks if network.version == 4
    )
    collapsed6 = ipaddress.collapse_addresses(
        network for network in networks if network.version == 6
    )
    ipv4 = sorted(
        collapsed4,
        key=lambda network: (int(network.network_address), network.prefixlen),
    )
    ipv6 = sorted(
        collapsed6,
        key=lambda network: (int(network.network_address), network.prefixlen),
    )
    return ipv4, ipv6


def nft_block(
    networks: list[ipaddress.IPv4Network] | list[ipaddress.IPv6Network],
    set_name: str,
) -> list[str]:
    lines = ["nft -f - <<EOF || _ret=1", f"add element $TARGET_TABLE {set_name} {{"]
    for index, network in enumerate(networks):
        suffix = "," if index + 1 < len(networks) else ""
        lines.append(f"  {network}{suffix}")
    lines.extend(["}", "EOF"])
    return lines


def render(
    ipv4: list[ipaddress.IPv4Network],
    ipv6: list[ipaddress.IPv6Network],
    source: str,
    target_interface: str,
) -> str:
    lines = [
        "#!/bin/sh",
        "# Generated by scripts/generate.py. Do not edit by hand.",
        f"# Source: {source}",
        f"# Networks: IPv4={len(ipv4)}, IPv6={len(ipv6)}",
        "# shellcheck shell=ash",
        "",
        "TARGET_TABLE='inet fw4'",
        f"TARGET_INTERFACE='{target_interface}'",
        "_ret=0",
        "",
    ]
    lines.extend(
        nft_block(ipv4, "pbr_${TARGET_INTERFACE}_4_dst_ip_user")
    )
    if ipv6:
        lines.extend(
            [
                "",
                "if [ \"$(uci -q get pbr.config.ipv6_enabled)\" = '1' ]; then",
            ]
        )
        lines.extend(
            f"  {line}" if line not in {"EOF"} else line
            for line in nft_block(ipv6, "pbr_${TARGET_INTERFACE}_6_dst_ip_user")
        )
        lines.append("fi")
    lines.extend(["", "( exit \"$_ret\" )", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=DEFAULT_SOURCE)
    parser.add_argument("--output", default="src/pbr.user.geoip-cn")
    parser.add_argument("--target-interface", default="wan")
    parser.add_argument("--minimum-ipv4", type=int, default=1000)
    parser.add_argument("--minimum-ipv6", type=int, default=10)
    args = parser.parse_args()

    if not args.target_interface or any(
        char not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
        for char in args.target_interface
    ):
        parser.error("--target-interface may contain only letters, numbers, _ and -")

    try:
        ipv4, ipv6 = parse_networks(read_source(args.source))
    except (RuntimeError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1

    if len(ipv4) < args.minimum_ipv4 or len(ipv6) < args.minimum_ipv6:
        print(
            "source validation failed: "
            f"got IPv4={len(ipv4)}, IPv6={len(ipv6)}; "
            f"minimums are IPv4={args.minimum_ipv4}, IPv6={args.minimum_ipv6}",
            file=sys.stderr,
        )
        return 1

    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(ipv4, ipv6, args.source, args.target_interface), encoding="utf-8")
    output.chmod(0o755)
    print(f"generated {output}: IPv4={len(ipv4)}, IPv6={len(ipv6)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
